<a href="https://colab.research.google.com/github/BillyImperial/ProjetoGit/blob/main/Day_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%writefile data.py
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

def start_pipeline(dataf):
    return dataf.copy()

def get_product_counts(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'customer_id': pd.Series.nunique}) \
    .rename(columns={'customer_id': 'customer_id_count'}) \
    .set_index('product_id') \
    .sort_values('customer_id_count', ascending = False)

def get_avg_ratings(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'review_score': np.mean}) \
    .rename(columns={'review_score': 'review_score_avg'}) \
    .set_index('product_id') \
    .sort_values('review_score_avg', ascending = False)

def get_n_top_values(dataf, n):
  return dataf.head(n) \
    .index \
    .tolist()

top_product_ratings = df \
  .pipe(start_pipeline) \
  .pipe(get_avg_ratings) \
  .pipe(get_n_top_values, n=1500)

top_product_sellers = df \
  .pipe(start_pipeline) \
  .pipe(get_product_counts) \
  .pipe(get_n_top_values, n=10)

top_product_ratings[:10], top_product_sellers 

Overwriting data.py


In [ ]:
%%writefile item_based_recommender.py
import random

import numpy as np

from data import get_data, get_item_based_similarity_matrix


class ItemBasedRecommender:

  def __init__(self, data_path):
    self.data_path = data_path

  def setup(self):
    data = get_data(self.data_path)
    sim_matrix, available_items_index = get_item_based_similarity_matrix(data)
    self.available_items_index = available_items_index
    self.sim_matrix = sim_matrix

  def get_random_item_index(self):
    item_id = self.available_items_index[random.randint(0, self.sim_matrix.shape[0])]
    return item_id

  def get_n_closest(self, item_id, n=10):
    if item_id not in self.available_items_index:
      raise ValueError('Item is not available on data.')
    item_index = self.available_items_index.tolist().index(item_id)
    closest_n_iten = np.argsort(-self.sim_matrix[item_index])[1:n]
    n_closest = []
    for item_data in zip(self.available_items_index[closest_n_iten], self.sim_matrix[item_index][closest_n_iten]):
      n_closest.append(item_data)
    return tuple(n_closest)

Writing item_based_recommender.py


#Setup do Sistema de Recomendação

In [ ]:
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [170]:
df_items = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Data Expert/Day 7/DNC_order_items_dataset.csv", index_col=0)

df_reviews = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Data Expert/Day 7/DNC_order_reviews_dataset.csv", index_col=0)

df_orders = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Data Expert/Day 7/DNC_orders_dataset.csv", index_col=0)

df_products = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Data Expert/Day 7/DNC_products_dataset.csv", index_col=0)

In [171]:
df1 = df_items.merge(df_products, how='inner', on='product_id')
df1.head()

order_id  ...  product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...              14.0
1  130898c0987d1801452a8ed92a670612  ...              14.0
2  532ed5e14e24ae1f0d735b91524b98b9  ...              14.0
3  6f8c31653edb8c83e1a739408b5ff750  ...              14.0
4  7d19f4ef4d04461989632411b7e588b9  ...              14.0

[5 rows x 11 columns]

In [172]:
df2 = df1.merge(df_reviews, how='inner', on='order_id')
df2.head()

order_id  ...  review_score
0  00010242fe8c5a6d1ba2dd792cb16214  ...             5
1  130898c0987d1801452a8ed92a670612  ...             5
2  532ed5e14e24ae1f0d735b91524b98b9  ...             4
3  6f8c31653edb8c83e1a739408b5ff750  ...             5
4  7d19f4ef4d04461989632411b7e588b9  ...             5

[5 rows x 13 columns]

In [173]:
df = df2.merge(df_orders, how='inner', on='order_id')
df.head()

order_id  ...  order_status
0  00010242fe8c5a6d1ba2dd792cb16214  ...     delivered
1  130898c0987d1801452a8ed92a670612  ...     delivered
2  532ed5e14e24ae1f0d735b91524b98b9  ...     delivered
3  6f8c31653edb8c83e1a739408b5ff750  ...     delivered
4  7d19f4ef4d04461989632411b7e588b9  ...     delivered

[5 rows x 15 columns]

In [192]:
df.shape

(112372, 15)

In [168]:
#df.drop(['order_id', 'order_item_id', 'price', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'review_id', 'order_status'],axis=1,inplace=True)

In [ ]:
df.head()

product_id  ...                       customer_id
0  4244733e06e7ecb4970a6e2683c13e61  ...  3ce436f183e68e07877b285a838db11a
1  4244733e06e7ecb4970a6e2683c13e61  ...  e6eecc5a77de221464d1c4eaff0a9b64
2  4244733e06e7ecb4970a6e2683c13e61  ...  4ef55bf80f711b372afebcb7c715344a
3  4244733e06e7ecb4970a6e2683c13e61  ...  30407a72ad8b3f4df4d15369126b20c9
4  4244733e06e7ecb4970a6e2683c13e61  ...  91a792fef70ecd8cc69d3c7feb3d12da

[5 rows x 3 columns]

In [ ]:
#df.drop(columns=['order_id', 'review_id', 'order_status'], inplace=True)

In [ ]:
df_top_produtos = df.groupby(by='product_id', as_index=False) \
    .agg({'customer_id': pd.Series.nunique}) \
    .rename(columns={'customer_id': 'customer_id_count'}) \
    .set_index('product_id') \
    .sort_values('customer_id_count', ascending = False)

In [ ]:
df_top_produtos.head()

customer_id_count
product_id                                         
99a4788cb24856965c36a24e339b6058                458
aca2eb7d00ea1a7b8ebd4e68314663af                429
422879e10f46682990de24d770e7f83d                351
d1c427060a0f73f6b889a5c7c61f2ac4                320
389d119b48cf3043d311335e499d9c6b                310

In [ ]:
df_top_reviews = df.groupby(by='product_id', as_index=False) \
    .agg({'review_score': np.mean}) \
    .rename(columns={'review_score': 'review_score_avg'}) \
    .set_index('product_id') \
    .sort_values('review_score_avg', ascending = False)

In [ ]:
df_top_reviews.head()

review_score_avg
product_id                                        
00066f42aeeb9f3007548bb9d3f33c38               5.0
60314cbf527af04ebc935be7c02dc1cd               5.0
5fe23e6307c231e287f13c0a4be06c88               5.0
5fe490e61e7a37f2f0d1ad1771ac027d               5.0
c696cd2db7870be08c37822f7c0ef831               5.0

In [ ]:
df.head()

order_id  ...  order_status
0  00010242fe8c5a6d1ba2dd792cb16214  ...     delivered
1  130898c0987d1801452a8ed92a670612  ...     delivered
2  532ed5e14e24ae1f0d735b91524b98b9  ...     delivered
3  6f8c31653edb8c83e1a739408b5ff750  ...     delivered
4  7d19f4ef4d04461989632411b7e588b9  ...     delivered

[5 rows x 15 columns]

In [174]:
df_drop = df.drop(columns=['order_id', 'order_item_id', 'review_id', 'customer_id', 'order_status'])

In [ ]:
#df_drop.drop(columns=['product_id'], inplace=True)

In [175]:
df_drop.shape

(112372, 10)

In [176]:
df_drop = df_drop.sample(1000)

In [177]:
df_product_id = df_drop['product_id']

In [178]:
df_drop.drop(columns=['product_id'], inplace=True)

In [179]:
df_drop_dummy = pd.get_dummies(df_drop)
df_drop_dummy.head()

price  ...  product_category_name_utilidades_domesticas
16574   40.8  ...                                            0
74266  334.8  ...                                            0
86936  130.0  ...                                            0
43434   39.9  ...                                            0
19285  149.9  ...                                            0

[5 rows x 58 columns]

In [180]:
df_drop_dummy = df_drop_dummy.fillna(0)

In [181]:
from sklearn.preprocessing import MinMaxScaler 

df_norm = MinMaxScaler()
df_norm1 = df_norm.fit_transform(df_drop_dummy.values)

In [182]:
matriz = np.zeros((1000,1000), dtype=np.float64) 

In [183]:
from scipy.spatial import distance 

for i in range(1000):
	for j in range(1000):
		matriz[i][j] = distance.euclidean(df_norm1[i], df_norm1[j]) 

In [184]:
print(matriz)

[[0.         1.42751402 1.44641907 ... 1.56614605 1.44559739 1.70879285]
 [1.42751402 0.         1.45316129 ... 1.56670946 1.45006975 1.70976198]
 [1.44641907 1.45316129 0.         ... 1.61666894 1.43062894 1.82177237]
 ...
 [1.56614605 1.56670946 1.61666894 ... 0.         1.66283152 0.51042406]
 [1.44559739 1.45006975 1.43062894 ... 1.66283152 0.         1.86264558]
 [1.70879285 1.70976198 1.82177237 ... 0.51042406 1.86264558 0.        ]]


In [185]:
df_matriz = pd.DataFrame(matriz)
df_matriz.head()

0         1         2    ...       997       998       999
0  0.000000  1.427514  1.446419  ...  1.566146  1.445597  1.708793
1  1.427514  0.000000  1.453161  ...  1.566709  1.450070  1.709762
2  1.446419  1.453161  0.000000  ...  1.616669  1.430629  1.821772
3  1.720975  1.708108  1.870342  ...  1.757852  1.845703  1.701728
4  1.594407  1.608360  1.552005  ...  1.566047  1.632057  1.794322

[5 rows x 1000 columns]

In [188]:
df_matriz.rename(columns=df_product_id, inplace=True)

In [189]:
df_matriz.head()

4244733e06e7ecb4970a6e2683c13e61  ...  368c6c730842d78016ad823897a372db
0                          0.000000  ...                          1.708793
1                          1.427514  ...                          1.709762
2                          1.446419  ...                          1.821772
3                          1.720975  ...                          1.701728
4                          1.594407  ...                          1.794322

[5 rows x 1000 columns]

In [190]:
df_matriz.set_index(df_product_id, inplace=True)

In [191]:
df_matriz

4244733e06e7ecb4970a6e2683c13e61  ...  368c6c730842d78016ad823897a372db
product_id                                                          ...                                  
84f5c4f480ad6c9998d6a6860f1a2e41                          0.000000  ...                          1.708793
21767347dfdabbe42b3ca5846a4cdb48                          1.427514  ...                          1.709762
b30d7b0adcdc4a117f455472548155ec                          1.446419  ...                          1.821772
ab330e1b64fde92d3b4d4d6980a38576                          1.720975  ...                          1.701728
25f86162fee18735fffdb762dcb10d7c                          1.594407  ...                          1.794322
...                                                            ...  ...                               ...
9bb8ca338e5588c361e34eae02e8fad6                          1.456196  ...                          1.745784
98a8c2fa16d7239c606640f5555768e4                          1.528279  ...                          1.817322
eab67bf937aaadc19f83383a331d2dd9                          1.566146  ...                          0.510424
377d0ea8bb2c8365af0b1519223d324a                          1.445597  ...                          1.862646
e8316a4667e5870c85e906b1f062bde1                          1.708793  ...                          0.000000

[1000 rows x 1000 columns]

In [213]:
top_csv = np.zeros((1,6),dtype=int)

for produto in range(0,df_matriz.shape[0]): # para cada cidade
  actual_produto = df_matriz.iloc[city]
  #print(cod_ibge)
  search = []
  for line in range(1,actual_city.shape[0]): # crio o dicionáário
      cod_produto = str(df_matriz.columns[line])
      dist = float(actual_produto[line])
      search.append((cod_produto, dist))

  search.sort(key=lambda x:x[1]) # ordeno pela distancia
  top5 = search[1:6] # pegar top5 cidades mais próximas
  regist = np.array([[ (actual_produto[0]),(top5[0][0]),(top5[1][0]),(top5[2][0]),(top5[3][0]),(top5[4][0]) ]] )
  top_csv = np.concatenate((top_csv,regist)) 

In [214]:
dataset = pd.DataFrame()
dataset['target_product'] = top_csv[:,0]
dataset['top1'] = top_csv[:,1]
dataset['top2'] = top_csv[:,2]
dataset['top3'] = top_csv[:,3]
dataset['top4'] = top_csv[:,4]
dataset['top5'] = top_csv[:,5]
dataset.drop(0,inplace=True) 

In [216]:
dataset.head()

target_product  ...                              top5
product_id                                            ...                                  
84f5c4f480ad6c9998d6a6860f1a2e41  1.7087928528424237  ...  99a4788cb24856965c36a24e339b6058
21767347dfdabbe42b3ca5846a4cdb48  1.7087928528424237  ...  99a4788cb24856965c36a24e339b6058
b30d7b0adcdc4a117f455472548155ec  1.7087928528424237  ...  99a4788cb24856965c36a24e339b6058
ab330e1b64fde92d3b4d4d6980a38576  1.7087928528424237  ...  99a4788cb24856965c36a24e339b6058
25f86162fee18735fffdb762dcb10d7c  1.7087928528424237  ...  99a4788cb24856965c36a24e339b6058

[5 rows x 6 columns]